---
- name: create install dir
  file:
    path: "{{ prca_privateca.install_path }}"
    state: directory

- name: put CA script
  template:
    src: CA.j2
    dest: /etc/pki/tls/misc/CA
    mode: "0755"
    owner: root
    group: root

- name: setting openssl conf
  template:
    src: openssl.cnf.j2
    dest: /etc/pki/tls/openssl.cnf
    mode: 0644
    owner: root
    group: root

- name: create CA
  shell: /etc/pki/tls/misc/CA -newca
  args:
    creates: "{{ prca_privateca.install_path }}/private/{{ prca_privateca.ca_cert.private_key_filename }}"
  environment:
    catop: "{{ prca_privateca.install_path }}"

- name: create der format cert
  shell: >
    openssl x509 -inform pem -in {{ prca_privateca.install_path }}/{{ prca_privateca.ca_cert.pem_filename }} \
       -outform der -out {{ prca_privateca.install_path }}/{{ prca_privateca.ca_cert.der_filename }}
  args:
    creates: "{{ prca_privateca.install_path }}/{{ prca_privateca.ca_cert.der_filename }}"
