---
- name: 1-1201-01_Install zabbix agent - install package
  yum:
    name: "{{ zabbix_agent.package }}"
    state: present
  when: zabbix_agent.package is defined

- name: 1-1301-01_install - put zabbix agent config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: zabbix_service_restart 
  when: zabbix_agent.config is defined

- meta: flush_handlers

- name: 1-1301-01_install - change service state
  service:
    name: zabbix-agent
    state: "{{ zabbix_agent.service.state }}"
  when: zabbix_agent | has_nested_keys("service", "state")
   
- name: 1-1301-01_install - change auto starting setting
  service:
    name: zabbix-agent
    enabled: "{{ zabbix_agent.service.enabled }}"
  when: zabbix_agent | has_nested_keys("service", "enabled")
