- block:
  - name: 1-0102-04_install_httpd2.4 - check installed package
    shell: rpm -qa | grep -q "{{ item.name | regex_replace('\.rpm', '') }}"
    register: installed
    changed_when: installed.rc == 1
    failed_when: installed.rc == 2
    with_items: apac_apache.packages | default("")

  - name: 1-0102-04_install_httpd2.4 - create temp directory
    file:
      path: "{{ apac_apache_tmp_dir }}"
      state: directory
    when: installed | changed

  - name: 1-0102-04_install_httpd2.4 - send package
    copy:
      src: "../Shift_Env/files/{{ item.name }}"
      dest: "{{ apac_apache_tmp_dir }}"
    with_items: apac_apache.packages | default("")
    register: send_task
    when: installed | changed

  - name: 1-0102-04_install_httpd2.4 - update package
    shell: "yum update -y *"
    args: 
      chdir: "{{ apac_apache_tmp_dir }}"
    when: installed | changed

  - name: 1-0102-04_install_httpd2.4 - install package
    yum:
      name: "{{ send_task.results | join(', ', attribute='dest') }}"
      state: present
    when: installed | changed
  when: apac_apache.packages is defined

- name: 1-0102-04_install_httpd2.4 - delete temp directory
  file:
    path: '{{ apac_apache_tmp_dir }}'
    state: absent

- name: 1-0102-04_install_httpd2.4 - put httpd.conf
  template: 
    src: httpd24.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart httpd

- name: 1-0102-04_install_httpd2.4 - put httpd-autoindex.conf
  template:
    src: httpd24-autoindex.conf.j2
    dest: /etc/httpd/conf/extra/httpd-autoindex.conf
  notify: restart httpd
  when: apac_apache.autoindex is defined

- name: 1-0102-04_install_httpd2.4 - put httpd-mpm.conf
  template:
    src: httpd24-mpm.conf.j2
    dest: /etc/httpd/conf/extra/httpd-mpm.conf
  notify: restart httpd
  when: apac_apache.mpm is defined

- name: 1-0102-04_install_httpd2.4 - put httpd-default.conf
  template:
    src: httpd24-default.conf.j2
    dest: /etc/httpd/conf/extra/httpd-default.conf
  notify: restart httpd

- name: 1-0102-04_install_httpd2.4 - put httpd-info.conf
  template:
    src: httpd24-info.conf.j2
    dest: /etc/httpd/conf/extra/httpd-info.conf
  notify: restart httpd
  when:
    - apac_apache.visible_server_status is defined or
      apac_apache.visible_server_info is defined

- name: 1-0102-04_install_httpd2.4 - put httpd-languages.conf
  template:
    src: httpd24-languages.conf.j2
    dest: /etc/httpd/conf/extra/httpd-languages.conf
  notify: restart httpd
  when:
    - apac_apache.is_default_charset_utf8 is defined or
      apac_apache.is_1st_prior_language_ja is defined

- name: 1-0102-04_install_httpd2.4 - put httpd-userdir.conf
  template:
    src: httpd24-userdir.conf.j2
    dest: /etc/httpd/conf/extra/httpd-userdir.conf
  notify: restart httpd
  when: apac_apache.disable_userdir is defined
