---
- name: 1-0105-01_install - install package
  yum:
    name: "java-{{ openjdk.version }}-openjdk"
    state: present

- name: 1-0105-01_install - install devel package
  yum:
    name: "java-{{ openjdk.version }}-openjdk-devel"
    state: present
  when: openjdk.install_devel
