---
- name: 2-9901_PreDev
  hosts: all
  user: Administrator
  vars_files:
    - var.yml
  tasks:
    - import_tasks: 2-9901-01_CreateTmp.yml
    - import_tasks: 2-9901-02_SendFiles.yml
    - import_tasks: 2-9901-03_ApplyHotfix.yml
      when: ansible_distribution_version | match("6\.2.*")
  handlers:
    - name: server_restart_for_Win
      raw: powershell "Restart-Computer -Force"

    - name: wait_for_WinRM_port_down
      wait_for: >
        host={{ inventory_hostname }}
        port=5986
        state=stopped
      delegate_to: 127.0.0.1

    - name: wait_for_WinRM_port_up
      wait_for: >
        host={{ inventory_hostname }}
        port=5986
        state=started
        delay=30
      delegate_to: 127.0.0.1
