---
- name: 1-0108-03_pgpool_config - put pgpool.conf
  copy:
    src: "{{ pgpl_pgpool.config.filename }}"
    dest: /etc/pgpool-II/pgpool.conf
  notify: pgpool_service_restart
  when: pgpl_pgpool | has_nested_keys('config', 'filename') 

- name: 1-0108-03_pgpool_config - configure pcp.conf
  lineinfile:
    dest: /etc/pgpool-II/pcp.conf
    line: "{{ item.name }}:{{ item.password | hash('md5') }}"
    regexp: "^{{ item.name }}:"
  notify: pgpool_service_restart
  with_items: "{{ pgpl_pgpool.pcp_users | default([]) }}"

- name: 1-0108-03_pgpool_config - configure pool_hba.conf when type == local
  lineinfile:
    dest: /etc/pgpool-II/pool_hba.conf
    line: "local {{ item.database }} {{ item.user }} {{ item.method }}"
    regexp: "^local *{{ item.database }} *{{ item.user }} *{{ item.method }}"
  notify: pgpool_service_restart
  with_items: "{{ pgpl_pgpool.pool_hba | default([]) }}"
  when: item.type == "local"

- name: 1-0108-03_pgpool_config - configure pool_hba.conf when type != local
  lineinfile:
    dest: /etc/pgpool-II/pool_hba.conf
    line: "{{ item.type }} {{ item.database }} {{ item.user }} {{ item.address }} {{ item.method }}"
    regexp: "^{{ item.type }} *{{ item.database }} *{{ item.user }} *{{ item.address }} *{{ item.method }}"
  notify: pgpool_service_restart
  with_items: "{{ pgpl_pgpool.pool_hba | default([]) }}"
  when: item.type != "local"

- include: config_pool_passwd.yml
  with_items: "{{ pgpl_pgpool.pool_passwd | default([]) }}"

- name: 1-0108-03_pgpool_config - set owner of config files
  file:
    path: /etc/pgpool-II
    owner: "{{ pgpl_pgpool.exec_user.name }}"
    recurse: yes
    state: directory
  when: pgpl_pgpool | has_nested_keys('exec_user', 'name')

