---
- meta: flush_handlers

- name: 1-0104-05_post_tasks - change postgresql service state
  service:
    name: "postgresql-{{ pgsq_postgresql.version }}"
    state: "{{ pgsq_postgresql.state }}"
  when: pgsq_postgresql.state is defined

- name: 1-0104-05_post_tasks - change auto starting setting of postgresql service
  service:
    name: "postgresql-{{ pgsq_postgresql.version }}"
    enabled: "{{ pgsq_postgresql.enabled }}"
  when: pgsq_postgresql.enabled is defined

