---
- name: 1-0104-03_postgresql_conf - put postgresql.conf
  copy:
    src: "../Shift_Env/files/{{ pgsq_postgresql.postgresql_conf.conf_file }}"
    dest: "/var/lib/pgsql/{{ pgsq_postgresql.version }}/data/postgresql.conf"
  notify: postgresql_service_restart
  when: pgsq_postgresql | has_nested_keys('postgresql_conf', 'conf_file')

- name: 1-0104-03_postgresql_conf - put pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/var/lib/pgsql/{{ pgsq_postgresql.version }}/data/pg_hba.conf"
  notify: postgresql_service_restart
  when: pgsq_postgresql | has_nested_keys('authentication', 'records')

