---
- name: set string of postgresql db super user name
  set_fact:
    pgsq_postgresql_db_user_name: "{{ pgsq_postgresql.db_user.name }}"
  when: pgsq_postgresql | has_nested_keys('db_user', 'name')

- name: set string of postgresql db default super user name
  set_fact:
    pgsq_postgresql_db_user_name: 'postgres'
  when: not (pgsq_postgresql | has_nested_keys('db_user', 'name'))

- import_tasks: 1-0104-01_create_user_and_groups.yml
- import_tasks: 1-0104-02_postgresql.yml

- block:
  - import_tasks: 1-0104-03_postgresql_conf.yml
  when:
    - (not (pgsq_postgresql | has_nested_keys('cluster', 'server_role')) or
      (pgsq_postgresql.cluster.server_role  == "")

# クラスタ構成の場合、ReplicationのためMasterを先に実行する
- block:
  - import_tasks: 1-0104-04_postgresql_replication.yml
  - import_tasks: 1-0104-03_postgresql_conf.yml
  when:
    - pgsq_postgresql | has_nested_keys('cluster', 'server_role')
    - pgsq_postgresql.cluster.server_role == "master"

- meta: flush_handlers

- block:
  - import_tasks: 1-0104-04_postgresql_replication.yml
  - import_tasks: 1-0104-03_postgresql_conf.yml
  when:
    - pgsq_postgresql | has_nested_keys('cluster', 'server_role')
    - pgsq_postgresql.cluster.server_role == "slave"

- import_tasks: 1-0104-05_post_tasks.yml
