---
- name: 2-0001-109_Organization - set tmp variable
  set_fact:
     org: "{{ base_ADVANCED.organization }}"
     location1: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'
     location2: 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion'

- name: 2-0001-104_Owner - set registry value
  win_regedit:
    path: "{{ item.location }}"
    name: "{{ item.property }}"
    data: "{{ item.data }}"
    type: "string"
  with_items:
  - location: '{{ location1 }}'
    property: "RegisteredOrganization"
    data: '{{ org }}'
  - location: '{{ location2 }}'
    property: "RegisteredOrganization"
    data: '{{ org }}'
