---
- name: 2-0001-077_IPv6Disable - set tmp variable
  set_fact:
    ipv6: "{{ base_NETWORK.ipv6 }}"
    location: 'HKLM:\SYSTEM\CurrentControlSet\Services\TCPIP6\Parameters'

- name: 2-0001-077_IPv6Disable - create registry path
  raw: if ( ! ( Test-Path '{{ location }}' )) { New-Item '{{ location }}' -Force }
  register: create_registry_path
  changed_when: create_registry_path.stdout != ""
  always_run: yes

- name: 2-0001-077_IPv6Disable - check registry value
  raw: (Get-ItemProperty '{{ location }}').DisabledComponents
  register: ret_pre
  when:
    - ipv6 | has_nested_keys('registry')
    - ipv6.registry == 'disabled'
  changed_when: ret_pre.stdout != "255\r\n"
  always_run: yes

- name: 2-0001-077_IPv6Disable - set registry value
  raw: Set-ItemProperty '{{ location }}' 'DisabledComponents' -Value '255' -Type 'dword'
  when:
    - ipv6 | has_nested_keys('registry')
    - ret_pre | changed
  always_run: no

- name: 2-0001-077_IPv6Disable - post check registry value
  raw: (Get-ItemProperty '{{ location }}').DisabledComponents
  register: ret_post
  when:
    - ipv6 | has_nested_keys('registry')
    - ipv6.registry == 'disabled'
    - ret_pre | changed
  changed_when: ret_pre.stdout != "255\r\n"
  always_run: no

- name: 2-0001-077_IPv6Disable - check ms_tcpip6 parameter
  raw: '{{ ipv6.nvspbind_path }} | Select-String "ms_tcpip6 "'
  when:
    - ipv6 | has_nested_keys('nic_property')
    - ipv6.nic_property == 'disabled'
  register: ret_pre
  changed_when: >
    ret_pre.stdout | search("enabled") or
    ret_pre.stdout | search("default")
  always_run: yes

- name: 2-0001-077_IPv6Disable - set ms_tcpip6 parameter disabled for all nics
  raw: '{{ ipv6.nvspbind_path }} /d * ms_tcpip6'
  when:
    - ipv6 | has_nested_keys('nic_property')
    - ipv6.nic_property == 'disabled'
    - ret_pre | changed
  failed_when: False
  always_run: no

- name: 2-0001-077_IPv6Disable - post check ms_tcpip6 parameter
  raw: '{{ ipv6.nvspbind_path }} | Select-String "ms_tcpip6 "'
  when:
    - ipv6 | has_nested_keys('nic_property')
    - ipv6.nic_property == 'disabled'
    - ret_pre | changed
  register: ret_post
  failed_when: >
    ret_post.stdout | search("enabled") or
    ret_post.stdout | search("default")
  always_run: no

- name: 2-0001-077_IPv6Disable - check isatap parameter
  raw: netsh interface ipv6 show interface
  when:
    - ipv6 | has_nested_keys('netsh_command', 'isatap_if')
    - ipv6.netsh_command.isatap_if == 'disabled'
  register: ret_pre
  changed_when: >
    ret_pre.stdout | search("isatap")
  always_run: yes

- name: 2-0001-077_IPv6Disable - set isatap parameter disabled
  raw: netsh interface ipv6 isatap set state disabled
  when:
    - ipv6 | has_nested_keys('netsh_command', 'isatap_if')
    - ipv6.netsh_command.isatap_if == 'disabled'
    - ret_pre | changed
  always_run: no

- name: 2-0001-077_IPv6Disable - post check isatap parameter
  raw: netsh interface ipv6 show interface
  when:
    - ipv6 | has_nested_keys('netsh_command', 'isatap_if')
    - ipv6.netsh_command.isatap_if == 'disabled'
    - ret_pre | changed
  register: ret_post
  failed_when: >
    ret_post.stdout | search("isatap")
  always_run: no

- name: 2-0001-077_IPv6Disable - check 6to4 parameter
  raw: netsh interface ipv6 show interface
  when:
    - ipv6 | has_nested_keys('netsh_command', 'sixtofour_if')
    - ipv6.netsh_command.sixtofour_if == 'disabled'
  register: ret_pre
  changed_when: >
    ret_pre.stdout | search("6TO4")
  always_run: yes

- name: 2-0001-077_IPv6Disable - set 6to4 parameter disabled
  raw: netsh interface ipv6 6to4 set state disabled
  when:
    - ipv6 | has_nested_keys('netsh_command', 'sixtofour_if')
    - ipv6.netsh_command.sixtofour_if == 'disabled'
    - ret_pre | changed
  always_run: no

- name: 2-0001-077_IPv6Disable - post check 6to4 parameter
  raw: netsh interface ipv6 show interface
  when:
    - ipv6 | has_nested_keys('netsh_command', 'sixtofour_if')
    - ipv6.netsh_command.sixtofour_if == 'disabled'
    - ret_pre | changed
  register: ret_post
  failed_when: >
    ret_post.stdout | search("6TO4")
  always_run: no

- name: 2-0001-077_IPv6Disable - check teredo parameter
  raw: netsh interface ipv6 show interface
  when:
    - ipv6 | has_nested_keys('netsh_command', 'teredo_if')
    - ipv6.netsh_command.teredo_if == 'disabled'
  register: ret_pre
  changed_when: >
    ret_pre.stdout | search("Teredo")
  always_run: yes

- name: 2-0001-077_IPv6Disable - set teredo parameter disabled
  raw: netsh interface teredo set state disabled
  when:
    - ipv6 | has_nested_keys('netsh_command', 'teredo_if')
    - ipv6.netsh_command.teredo_if == 'disabled'
    - ret_pre | changed
  always_run: no

- name: 2-0001-077_IPv6Disable - post check teredo parameter
  raw: netsh interface ipv6 show interface
  when:
    - ipv6 | has_nested_keys('netsh_command', 'teredo_if')
    - ipv6.netsh_command.teredo_if == 'disabled'
    - ret_pre | changed
  register: ret_post
  failed_when: >
    ret_pre.stdout | search("Teredo")
  always_run: no

