---
- name: 2-0001-073_Routing - set tmp empty variable "static_routing"
  set_fact:
    static_routing: []
  when: base_NETWORK.static_routing is undefined

- name: 2-0001-073_Routing - set tmp variable "static_routing"
  set_fact:
    static_routing: "{{ base_NETWORK.static_routing }}"
  when: base_NETWORK.static_routing is defined

- name: 2-0001-073_Routing - set tmp variable "default_gw"
  set_fact:
    default_gw: "{{ base_NETWORK.default_gw }}"
  when: base_NETWORK.default_gw is defined

- name: 2-0001-073_Routing - check static route
  raw: route print -4 '{{ item.dest }}' | Select-String '{{ item.dest }}'
  with_items: static_routing
  register: ret_pre
  changed_when: not ret_pre.stdout | search("\s{{ item.dest }}\s+{{ item.mask }}\s+{{ item.gw }}\s")
  always_run: yes

- name: 2-0001-073_Routing - set static route entry
  raw: route -p add '{{ item.item.dest }}' mask '{{ item.item.mask }}' '{{ item.item.gw }}'
  with_items: ret_pre.results
  when:
    - item.changed == true
  always_run: no

- name: 2-0001-073_Routing - post check static route
  raw: route print -4 '{{ item.dest }}' | Select-String '{{ item.dest }}'
  with_items: static_routing
  register: ret_post
  when:
    - ret_pre | changed
  failed_when: not ret_post.stdout | search("\s{{ item.dest }}\s+{{ item.mask }}\s+{{ item.gw }}\s")
  always_run: no

- name: 2-0001-073_Routing - check default route
  raw: route print -4 '0.0.0.0' | Select-String '0.0.0.0'
  register: ret_pre
  changed_when: not ret_pre.stdout | search("\s0\.0\.0\.0\s+0\.0\.0\.0\s+{{ default_gw }}\s")
  always_run: yes

- name: 2-0001-073_Routing - set default route when present route is empty
  raw: route -p add '0.0.0.0' mask '0.0.0.0' '{{ default_gw }}'
  when:
    - default_gw is defined
    - ret_pre | changed
    - ret_pre.stdout == ""
  always_run: no

- name: 2-0001-073_Routing - set default route when present route exists
  raw: route -p change '0.0.0.0' mask '0.0.0.0' '{{ default_gw }}'
  when:
    - default_gw is defined
    - ret_pre | changed
    - ret_pre.stdout != ""
  always_run: no

- name: 2-0001-073_Routing - post check default route
  raw: route print -4 '0.0.0.0' | Select-String '0.0.0.0'
  register: ret_post
  when:
    - default_gw is defined
    - ret_pre | changed
  failed_when: not ret_post.stdout | search("\s0\.0\.0\.0\s+0\.0\.0\.0\s+{{ default_gw }}\s")
  always_run: no
