---
- name: 2-0001-079_NameResolve - set tmp variable
  set_fact:
    name_resolve: "{{ base_NETWORK.name_resolve }}"

- name: 2-0001-079_NameResolve - check disignation of dns server
  raw: (Get-DnsClientServerAddress -InterfaceAlias "{{ name_resolve.dns_server.nic_name}}" -AddressFamily IPv4).ServerAddresses
  with_items: name_resolve.dns_server.server
  register: ret_pre
  changed_when: not ret_pre.stdout | search('(^|\r\n){{ item.ip }}(\r\n|$)')
  always_run: yes

- name: 2-0001-079_NameResolve - set disignation of dns server
  raw: >
    Set-DnsClientServerAddress -InterfaceAlias "{{ name_resolve.dns_server.nic_name }}" `
      -ServerAddresses "{{ name_resolve.dns_server.server | join(',', attribute='ip') }}"
  when: ret_pre | changed
  always_run: no

- name: 2-0001-079_NameResolve - post check disignation of dns server
  raw: (Get-DnsClientServerAddress -InterfaceAlias "{{ name_resolve.dns_server.nic_name}}" -AddressFamily IPv4).ServerAddresses
  with_items: name_resolve.dns_server.server
  register: ret_post
  when: ret_pre | changed
  failed_when: not ret_post.stdout | search('(^|\r\n){{ item.ip }}(\r\n|$)')
  always_run: no


- name: 2-0001-079_NameResolve - set hosts
  win_lineinfile:
    dest: 'C:\windows\system32\drivers\etc\hosts'
    regexp: '^#?\s*{{ item.ip | regex_escape() }}\s'
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items: name_resolve.hosts_records

