---
- name: 2-0001-102_ErrorReport - set tmp variable
  set_fact:
    error_report: "{{ base_ADVANCED.error_report }}"
    location: 'HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting'

- name: 2-0001-102_ErrorReport - set variable "flag" for powershell 0
  set_fact:
    flag: "0"
  when: error_report == "enabled"

- name: 2-0001-102_ErrorReport - set variable "flag" for powershell 1
  set_fact:
    flag: "1"
  when: error_report == "disabled"

- name: 2-0001-102_ErrorReport - set registry value
  win_regedit:
    path: "{{ location }}"
    name: "Disabled"
    data: "{{ flag }}"
    type: "dword"

