---
- name: 2-0001-106_Registry - set tmp empty variable
  set_fact:
     registry: []
  when: not base_ADVANCED | has_nested_keys('registry')

- name: 2-0001-106_Registry - set tmp variable
  set_fact:
     registry: "{{ base_ADVANCED.registry }}"
  when: base_ADVANCED | has_nested_keys('registry')

- name: 2-0001-106_Registry -set registry value
  win_regedit:
    path: "{{ item.0.key }}"
    name: "{{ item.1.name }}"
    data: "{{ item.1.data }}"
    type: "{{ item.1.type }}"
  with_subelements:
    - "{{ registry }}"
    - value
