---
- name: 2-0001-105_EventLog - set tmp variable
  set_fact:
    eventlog: "{{ base_ADVANCED.eventlog }}"

- name: 2-0001-105_EventLog - set registry "AutoBackupLogFiles" value when type is "overrite" or "none"
  win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item.key | capitalize }}"
    name: "AutoBackupLogFiles"
    data: "0"
    type: "dword"
  with_dict: "{{ eventlog }}"
  when: item.value.type == "overwirte" or item.value.type == "none"

- name: 2-0001-105_EventLog - set registry "AutoBackupLogFiles" value when type is "archive"
  win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item.key | capitalize }}"
    name: "AutoBackupLogFiles"
    data: "1"
    type: "dword"
  with_dict: "{{ eventlog }}"
  when: item.value.type == "archive"

- name: 2-0001-105_EventLog - set registry "Retention" value when type is "override"
  win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item.key | capitalize }}"
    name: "Retention"
    data: "0"
    type: "dword"
  with_dict: "{{ eventlog }}"
  when: item.value.type == "overwrite"

- name: 2-0001-105_EventLog - set registry "Retention" value when type is "archive" or "none"
  win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item.key | capitalize }}"
    name: "Retention"
    data: "4294967295"
    type: "dword"
  with_dict: "{{ eventlog }}"
  when: item.value.type == "archive" or item.value.type == "none"

- name: 2-0001-105_EventLog - set MaximumSize of Eventlog 
  win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item.key | capitalize }}"
    name: "MaxSize"
    data: "{{ item.value.maxsize * 1024 }}"
    type: "dword"
  with_dict: "{{ eventlog }}"

- name: 2-0001-105_EventLog - set Path of Eventlog 
  win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item.key | capitalize }}"
    name: "File"
    data: "{{ item.value.filepath }}"
    type: "expandstring"
  with_dict: "{{ eventlog }}"
