---
- name: 2-0001-103_WinUpdate - set tmp variable
  set_fact:
    windows_update: "{{ base_ADVANCED.windows_update }}"
    location: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update'

- name: 2-0001-103_WinUpdate - set variable "flag" for powershell 4
  set_fact:
    flag: "4"
  when: windows_update == "autoinstall"

- name: 2-0001-103_WinUpdate - set variable "flag" for powershell 3
  set_fact:
    flag: "3"
  when: windows_update == "downloadonly"

- name: 2-0001-103_WinUpdate - set variable "flag" for powershell 2
  set_fact:
    flag: "2"
  when: windows_update == "checkonly"

- name: 2-0001-103_WinUpdate - set variable "flag" for powershell 1
  set_fact:
    flag: "1"
  when: windows_update == "disabled"

- name: 2-0001-103_WinUpdate - set registry value
  win_regedit:
    path: "{{ location }}"
    name: "AUOptions"
    data: "{{ flag }}"
    type: "dword"

