---
- name: 2-0001-025_RecoverOs - define tmp variable
  set_fact:
     recover_os: "{{ base_BASE.OSCORE.recover_os }}"
     location: 'HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl'
  when: base_BASE | has_nested_keys('OSCORE', 'recover_os')

- name: 2-0001-025_RecoverOs - set variable "write_eventlog_flg" for powershell 1
  set_fact:
    write_eventlog_flg: "1"
  when:
    - recover_os | has_nested_keys('write_eventlog')
    - recover_os.write_eventlog == true

- name: 2-0001-025_RecoverOs - set variable "write_eventlog_flg" for powershell 0
  set_fact:
    write_eventlog_flg: "0"
  when:
    - recover_os | has_nested_keys('write_eventlog')
    - recover_os.write_eventlog == false

- name: 2-0001-025_RecoverOs - set variable "auto_reboot_flg" for powershell 1
  set_fact:
    auto_reboot_flg: "1"
  when:
    - recover_os | has_nested_keys('auto_reboot')
    - recover_os.auto_reboot == true

- name: 2-0001-025_RecoverOs - set variable "auto_reboot_flg" for powershell 0
  set_fact:
    auto_reboot_flg: "0"
  when:
    - recover_os | has_nested_keys('auto_reboot')
    - recover_os.auto_reboot == false

- name: 2-0001-025_RecoverOs - set variable "type_flg" for powershell 0
  set_fact:
    type_flg: "0"
  when:
    - recover_os | has_nested_keys('dumpfile', 'type')
    - recover_os.dumpfile.type == "none"

- name: 2-0001-025_RecoverOs - set variable "type_flg" for powershell 1
  set_fact:
    type_flg: "1"
  when:
    - recover_os | has_nested_keys('dumpfile', 'type')
    - recover_os.dumpfile.type == "minimum"

- name: 2-0001-025_RecoverOs - set variable "type_flg" for powershell 2
  set_fact:
    type_flg: "2"
  when:
    - recover_os | has_nested_keys('dumpfile', 'type')
    - recover_os.dumpfile.type == "kernel"

- name: 2-0001-025_RecoverOs - set variable "type_flg" for powershell 3
  set_fact:
    type_flg: "3"
  when:
    - recover_os | has_nested_keys('dumpfile', 'type')
    - recover_os.dumpfile.type == "full"

- name: 2-0001-025_RecoverOs - set variable "type_flg" for powershell 7
  set_fact:
    type_flg: "7"
  when:
    - recover_os | has_nested_keys('dumpfile', 'type')
    - recover_os.dumpfile.type == "auto"

- name: 2-0001-025_RecoverOs - set variable "overwrite_flg" for powershell 1
  set_fact:
    overwrite_flg: "1"
  when:
    - recover_os | has_nested_keys('dumpfile', 'overwrite')
    - recover_os.dumpfile.overwrite == true

- name: 2-0001-025_RecoverOs - set variable "overwrite_flg" for powershell 0
  set_fact:
    overwrite_flg: "0"
  when:
    - recover_os | has_nested_keys('dumpfile', 'overwrite')
    - recover_os.dumpfile.overwrite == false


- name: 2-0001-025_RecoverOs - set registry 
  win_regedit:
    path: "{{ location }}"
    name: "{{ item.property }}"
    data: "{{ item.value }}"
    type: "{{ item.type }}"
  with_items:
    - property: "LogEvent"
      value: "{{ write_eventlog_flg | default('') }}"
      type: "dword"
    - property: "AutoReboot"
      value: "{{ auto_reboot_flg | default('') }}"
      type: "dword"
    - property: "CrashDumpEnabled"
      value: "{{ type_flg | default('') }}"
      type: "dword"
    - property: "DumpFile"
      value: "{{ recover_os.dumpfile.path | default('') }}"
      type: "ExpandString"
    - property: "Overwrite"
      value: "{{ overwrite_flg | default('') }}"
      type: "dword"


- name: 2-0001-025_RecoverOs - check parameter of time to display os list
  raw: bcdedit /enum BOOTMGR
  register: ret_pre
  when: recover_os | has_nested_keys('display_os_list_time')
  changed_when: not ret_pre.stdout | search("\r\ntimeout\s+{{ recover_os.display_os_list_time }}\r\n")
  always_run: yes

- name: 2-0001-025_RecoverOs - set parameter of time to display os list
  raw: bcdedit /timeout "{{ recover_os.display_os_list_time }}"
  when:
    - recover_os | has_nested_keys('display_os_list_time')
    - ret_pre | changed
  always_run: no

- name: 2-0001-025_RecoverOs - post check parameter of time to display os list
  raw: bcdedit /enum BOOTMGR
  register: ret_post
  when:
    - recover_os | has_nested_keys('display_os_list_time')
    - ret_pre | changed
  failed_when: not ret_post.stdout | search("\r\ntimeout\s+{{ recover_os.display_os_list_time }}\r\n")
always_run: no
